version: "3.9"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    user: ${DB_USER}
    volumes:
      - ./pg_data:/var/lib/postgresql/data:rw
    environment:
      - PG_DATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432
    shm_size: "1gb"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    network_mode: bridge
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSLMODE=${DB_SSLMODE}
    expose:
      - 3001
    ports:
      - 3001:3001
    links:
      - db:db
    network_mode: bridge
